kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io/v1
  kind: Role
  name: role
subjects:
  - kind: ServiceAccount
    name: sa
    namespace: spi-system
